---
ip: "192.168.7.7"
memory: 2048
cpus: 1

networking:
    - public: true

folders:
    - map: .
      to: /var/www/

# PHP options: 5 (uses 5.6) or 7
php: 7

# Uses nginx + PHP-FPM. If set to false, uses Apache.
nginx: false

# ports:
#     - guest: 80
#       host: 8000